const testActionTypes = {
  UPDATE_MESSAGE_REQUEST: "UPDATE_MESSAGE_REQUEST",
  UPDATE_MESSAGE_SUCCESS: "UPDATE_MESSAGE_SUCCESS",
  UPDATE_MESSAGE_FAILURE: "UPDATE_MESSAGE_FAILURE",
};

export default testActionTypes;